### ISSUE TITLE
feat: handling memory limit

### ISSUE THREAD

**Issue by pashtet86** [ziaadini/nuxt-perfect-cache#1]
Hi, thank you very much for your work on this package.

I'm trying to envisage some edge cases in production and I'm wondering how I can handle situation when memory limit reached?

``` 
OOM command not allowed when used memory > 'maxmemory'.
  at parseError (node_modules/redis-parser/lib/parser.js:179:12)
  at parseType (node_modules/redis-parser/lib/parser.js:302:14)

 WARN  This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
```

**Comment by ziaadini** [comment]
okay that is because your memory limitation reached to solve this you can config your redis with eviction algorithm
i suggest LFU.
for more details see this topic
https://redis.io/topics/lru-cache
