### ISSUE TITLE
[Security] Redis url will be exposed

### ISSUE THREAD

**Issue by BatuhanK** [ziaadini/nuxt-perfect-cache#12]
<img width="1107" alt="Screen Shot 2021-10-01 at 22 57 31" src="https://user-images.githubusercontent.com/4688083/135679258-ba57795d-80b9-4332-86d7-9eeb3fea0d49.png">
Hello all and @ziaadini 
Because `nuxt.config.js` will be added to production bundle, your redis credentials will be exposed to public.
Some use cases has private redis (like yours) but some will be public redis with password protection. If they will use this package, their credentials will leak.

Please add a warning message or find a way to hide redis url from bundle.

**Comment by ziaadini** [comment]
thanks for your report i added a warning in doc
