### ISSUE TITLE
Share cache between client and ssr

### ISSUE THREAD

**Issue by jakubm95** [ziaadini/nuxt-perfect-cache#2]
Hello,

after refreshing, it retrieves queries from the cache, but when I change the routing, it still fetches this query.

Is this the assumption? It would be important for me to download the query once, that it would always be cached.

**Comment by ziaadini** [comment]
Hello it's not possible to access to redis in client side and in server side you don't access to localStorage and cookies have some memory limitations you can handle it by your own in client side in mounted.
if you have another idea please let me know
