### ISSUE TITLE
Use cacheFetch inside fetch hook?

### ISSUE THREAD

**Issue by NicoFerna** [ziaadini/nuxt-perfect-cache#7]
Hi, 

When I use cacheFetch inside a fetch hook on a component, the data is retrieved but not cached in Redis. It works fine when I then reload the page. 
Is it possible to achieve this?
(for more context, I posted [this](https://stackoverflow.com/questions/67892752/nuxtjs-redis-cache-implementation-for-api-calls-inside-components) on stackoverflow)

**Comment by ziaadini** [comment]
redis is only available in server side not client side when you are navigating in client side you don't have access to redis you can set absolute link to render server side when user is navigating but I don't recommend this. the best solution is cache data in redis in your api.
